config/routes.rb
EbayTest::Application.routes.draw do
  get "auth/new", to: "auth_callback#new"
  get "auth/bind", to: "auth_callback#create"

  resources :listings
  resources :notifications
  resource :setup do
    post "notifications", to: "setups#notifications"
  end
  resources :orders
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user

  attr_protected nil
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  include Deterministic::Prelude::Result

  private

  def authenticate
    redirect_to "/auth/new" unless current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def ebay
    @ebay ||= Ebay::Api.new(:auth_token => current_user.auth_token)
  end

  # Convert routine exceptions into soft failures
  def wrap_error
    begin
      Success(yield)
    rescue Ebay::RequestError => e
      Failure(e)
    end
  end
end

app/controllers/auth_callback_controller.rb
class AuthCallbackController < ApplicationController
  skip_before_filter :authenticate

  def new
    runame = ENV['EBAY_RU_NAME']

    ebay = Ebay::Api.new
    response = ebay.get_session_id(ru_name: runame)

    query = {
      RUName: runame,
      SessID: response.session_id,
      ruparams: {
        sid: response.session_id
      }.to_query
    }.to_query

    redirect_to "https://signin.sandbox.ebay.com/ws/eBayISAPI.dll?SignIn&#{query}"
  rescue Ebay::RequestError => e
    e.errors.each do |error|
      puts error.long_message
    end
    raise
  end


  def create
    ebay = Ebay::Api.new
    response = ebay.fetch_token(session_id: params[:sid])

    @user = User.find_or_initialize_by_username(params[:username])
    @user.auth_token = response.ebay_auth_token
    @user.save!

    session[:user_id] = @user.id

    redirect_to listings_path
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include Ebay::Types

  def new
  end

  def create
    @listing = current_user.listings.build(params.slice(:name, :sku))

    wrap_error { ebay.add_fixed_price_item(item: build_item(@listing)) }.
    map { |response|
      @listing.ebay_uid = response.item_id
      @listing.save!

      Success(response)
    }.
    map_err { |e|
      if e.errors.map(&:short_message).grep(/Specified SKU is in use/).any?
        wrap_error { ebay.revise_fixed_price_item(item: build_item(@listing)) }
      else
        Failure(e)
      end
    }.
    match do
      Success {
        redirect_to listings_path
      }
      Failure { |e|
        @errors = e.errors.map(&:long_message)
        render :new
      }
    end
  end

  def index
    @listings = current_user.listings
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])

    wrap_error { ebay.revise_fixed_price_item(:item => build_item(@listing)) }.
    match do
      Success {
        redirect_to listings_path
      }
      Failure { |e|
        @errors = e.errors.map(&:long_message)
        render :edit
      }
    end
  end

  private

  def build_item(listing)
    # Wine: 26270
    # Red Wine: 38182

    Item.new(
      :primary_category => Category.new(:category_id => 38182),
      :category_mapping_allowed => true,
      :title => listing.name,
      :sku => listing.sku,
      :application_data => "Created by Drync",
      :auto_pay => true,
      :description => 'Probably a wine. Probably in a bottle.',
      :inventory_tracking_method => InventoryTrackingMethodCode::SKU,
      :location => 'Somerville, MA',
      :postal_code => '02144',
      :start_price => Money.new(params[:price], 'USD'),
      :quantity => params[:quantity].to_i,
      :listing_duration => ListingDurationCode::GTC,
      :country => 'US',
      :currency => 'USD',
      :payment_methods => [BuyerPaymentMethodCode::PayPal],
      :paypal_email_address => ENV['EBAY_PAYPAL_EMAIL'],
      :condition_id => 1000, # Probably means New
      :dispatch_time_max => 4, # Handling time in days,
      :return_policy => ReturnPolicy.new(
        :description => "We'll keep your money forever, with no recourse.",
        :returns_accepted_option => ReturnsAcceptedOptionsCode::ReturnsNotAccepted
      ),
      :pickup_in_store_details => PickupInStoreDetails.new(
        :eligible_for_pickup_in_store => true
      ),
      :shipping_details => ShippingDetails.new(
        :shipping_type => ShippingTypeCode::Flat,
        :shipping_service_options => [
          ShippingServiceOptions.new(
            :shipping_service_priority => 1,
            :shipping_service => ShippingServiceCode::UPSGround,  # This does not seem to like FedexGround....
            :shipping_service_cost => Money.new(1150, 'USD'),
            :shipping_service_additional_cost => Money.new(150, 'USD')
          )
        ]
      )
    )
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  skip_before_filter :authenticate

  def create
    render :xml => request.body
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Ebay::Types

  def index
    wrap_error {
      ebay.get_orders(
        # :order_status => OrderStatusCode::Active,
        :order_role => TradingRoleCode::Seller,
        :number_of_days => 7
        )
    }.
    fmap { |response|
      response.orders
    }.
    match {
      Success { |orders|
        @orders = orders
      }
      Failure { |e|
        @orders = []
        flash.now[:alert] = e.errors.map(&:long_message).join("\n")
      }
    }

  end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  include Ebay::Types

  def show
  end

  def notifications
    wrap_error {
      ebay.set_notification_preferences(
        :application_delivery_preferences => ApplicationDeliveryPreferences.new(
          :application_enable => EnableCode::Enable,
          :application_url => "https://ixbnor27yd11.runscope.net" # TODO: move me to the env
        ))
    }.
    match {
      Success { render :text => "OK" }
      Failure { |e| render :text => e.errors.map(&:long_message).join("\n") }
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EbayTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if alert = flash[:alert] %>
  <div class="flash alert">
    <%= simple_format alert %>
  </div>
  <% end %>

  <% if notice = flash[:notice] %>
  <div class="flash notice">
    <%= simple_format notice %>
  </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/listings/edit.html.erb
<%= form_tag listing_path(@listing), method: 'PUT' do %>
<% if @errors.present? %>
  <ul>
  <% @errors.each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ul>
<% end %>
  <p>
    <label>Quantity</label>
    <%= text_field_tag "quantity" %>
  </p>
  <p>
    <label>Price</label>
    <%= text_field_tag "price" %>
  </p>
  <%= submit_tag "Submit" %>
<% end %>

app/views/listings/index.html.erb
<ul>
<% @listings.each do |listing| %>
  <li>
    <%= link_to listing.name, "http://cgi.sandbox.ebay.com/#{listing.ebay_uid}", :target => '_blank' %>
    <%= link_to 'edit', edit_listing_path(listing) %>
  </li>
<% end %>
</ul>

<%= link_to "New Listing", new_listing_path %>

app/views/listings/new.html.erb
<%= form_tag listings_path do %>
<% if @errors.present? %>
  <ul>
  <% @errors.each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ul>
<% end %>
   
  <p>
    <label>SKU</label>
    <%= text_field_tag "sku" %>
  </p>
  <p>
    <label>Name</label>
    <%= text_field_tag "name" %>
  </p>
  <%= submit_tag "Submit" %>
<% end %>

app/views/orders/index.html.erb
<div>
<% @orders.each do |order| %>
  <h3><%= number_to_currency(order.total) %> <%= order.order_id %></h3>
  <ul>
  <% order.transactions.each do |t| %>
    <li><%= t.item.title %></li>
  <% end %>
  </ul>
<% end %>
</div>

app/views/setups/show.html.erb
<p>
  Install notification handler <%= button_to 'Install', notifications_setup_path %>
</p>